/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4f422cab-0e72-498b-9095-78b8876d0642",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_unIaWsXdk",
    "aws_user_pools_web_client_id": "4cc1sdfkpmimg8tl87o97spg5m",
    "oauth": {}
};


export default awsmobile;
